/**
 * Playwright globalTeardown: remove the ephemeral SQLite DB generated by
 * playwright.config.ts. Best-effort — an error here does not fail the run
 * because the temp file lives in /tmp and will be cleaned by OS rotation.
 */

import { unlinkSync } from "node:fs";
import { ephemeralDbPath } from "../playwright.config";

export default async function globalTeardown(): Promise<void> {
  try {
    unlinkSync(ephemeralDbPath);
  } catch (error) {
    // File already gone or permission denied — not worth failing the run.
    console.warn(
      `[e2e teardown] Could not delete ${ephemeralDbPath}: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
  }
}
